sudo : required
services:
        - docker
before_install:
        - docker build -t trinadhkavuri/reactjs -f Dockerfile.DEV .

script:
        - docker run -e CI=true trinadhkavuri/reactjs npm run test -- --coverage

deploy:
        edge: true
        provider: "elasticbeanstack"
        region: "us-east-2"
        app:  "docker-reactjs"
        env: "DockerReactjs-env"
        bucket_name: "elasticbeanstalk-us-east-2-363556250113"
        bucket_path: "docker-reactjs"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY

